/**
 * Bundle all MiniLM model files as base64 constants into a TypeScript file.
 * These get compiled into the binary — no filesystem access needed at runtime.
 *
 * Run: bun run scripts/generate-embedding-model.ts
 *
 * Output: src/generated/embedding-model.ts (~31 MB base64)
 * At runtime, vector.ts extracts these to a temp directory for @xenova.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const lmFile = (await Bun.file("bee.lm.json").json().catch(() => ({}))) as Record<string, string>;
const MODEL_NAME = lmFile.embeddingModel ?? lmFile.CB_EMBEDDING_MODEL ?? process.env.CB_EMBEDDING_MODEL ?? "Xenova/all-MiniLM-L6-v2";
const parts = MODEL_NAME.split("/");
const MODEL_DIR = join(...parts);

const CACHE = join(import.meta.dir, "..", "node_modules", "@xenova", "transformers", ".cache", ...parts);
const MODELS = join(import.meta.dir, "..", "node_modules", "@xenova", "transformers", "models");

const files: { path: string; data: string }[] = [];

// 1. Model-specific files (config, tokenizer, onnx)
function walk(dir: string) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      walk(full);
    } else {
      const data = readFileSync(full);
      files.push({
        path: MODEL_DIR + "/" + relative(CACHE, full),
        data: data.toString("base64"),
      });
    }
  }
}
walk(CACHE);

// 2. @xenova's shared model registry files (needed for pipeline loading)
function walkModels(dir: string, prefix: string) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      walkModels(full, prefix + "/" + name);
    } else {
      const data = readFileSync(full);
      files.push({
        path: (prefix + "/" + name).replace(/^\//, ""),
        data: data.toString("base64"),
      });
    }
  }
}
const REGISTRY = join(MODELS, ...parts);
if (statSync(REGISTRY, { throwIfNoEntry: false })) {
  walkModels(REGISTRY, "models/" + MODEL_DIR);
}

let totalBytes = 0;
const entries = files.map((f) => {
  totalBytes += f.data.length;
  return `  ["${f.path}"]: "${f.data}"`;
});

const outPath = join(import.meta.dir, "..", "src", "generated", "embedding-model.ts");
const code = [
  "// Auto-generated by scripts/generate-embedding-model.ts — do not edit.",
  `// ${files.length} files, ${(totalBytes / 1024 / 1024).toFixed(1)} MB base64`,
  "// Extracted to a temp directory at runtime for @xenova/transformers.",
  "",
  "export const MODEL_FILES: Record<string, string> = {",
  entries.join(",\n"),
  "};",
].join("\n");

writeFileSync(outPath, code, "utf-8");
console.log(`✓ ${files.length} files (${(totalBytes / 1024 / 1024).toFixed(1)} MB base64) → ${outPath}`);
