/**
 * Pre-compute neural embeddings for the entire corpus using the configured
 * API embedding endpoint (CB_EMBEDDING_URL / bee.lm.json).
 *
 * The generated file is committed and baked into the binary — no model
 * needed at runtime.
 *
 * Run: bun run scripts/generate-embeddings.ts
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { Command } from "commander";

const lmFile = (await Bun.file("bee.lm.json").json().catch(() => ({}))) as Record<string, string>;
const MODEL_NAME = lmFile.embeddingModel ?? lmFile.CB_EMBEDDING_MODEL ?? process.env.CB_EMBEDDING_MODEL ?? "default";
const BASE_URL = lmFile.url ?? lmFile.CB_LM_URL ?? process.env.CB_LM_URL ?? "";
const API_KEY = lmFile.apiKey ?? lmFile.CB_API_KEY ?? process.env.CB_API_KEY ?? "";
const EMBEDDING_URL_OVERRIDE = lmFile.embeddingUrl ?? lmFile.CB_EMBEDDING_URL ?? process.env.CB_EMBEDDING_URL ?? "";
const API_URL = EMBEDDING_URL_OVERRIDE ||
  (BASE_URL ? `${BASE_URL.replace(/\/+$/, "")}/v1/embeddings` : "");

const { initPlugins } = await import("../src/registry");
const { buildCorpus } = await import("../src/plugins/docs/corpus");

console.log("Building corpus…");
const program = new Command("bee");
program.exitOverride();
await initPlugins(program);
const corpus = buildCorpus(program);

if (!API_URL) {
  console.error("ERROR: No embedding API configured. Set CB_EMBEDDING_URL or CB_LM_URL in bee.lm.json or env.");
  process.exit(1);
}

const headers: Record<string, string> = { "content-type": "application/json" };
if (API_KEY) {
  headers["authorization"] = `Bearer ${API_KEY}`;
  headers["x-api-key"] = API_KEY;
}
const embed = async (t: string): Promise<number[]> => {
  const r = await fetch(API_URL, {
    method: "POST",
    headers,
    body: JSON.stringify({ input: t.slice(0, 2048), model: MODEL_NAME }),
    signal: AbortSignal.timeout(30000),
  });
  if (r.ok) {
    const j = (await r.json()) as { data?: Array<{ embedding: number[] }> };
    return j.data?.[0]?.embedding ?? [];
  }
  throw new Error(`Embedding API returned ${r.status} at ${API_URL}`);
};
console.log("Using API embedding…");
const first = await embed(corpus[0]!.title);
const DIM = first.length;

const ids: string[] = [];
const values: number[] = [];

for (const item of corpus) {
  const text = [item.title, item.description, item.body].filter(Boolean).join(" ").slice(0, 512);
  const result = await embed(text);
  const vec = Array.from(result) as number[];
  ids.push(item.id);
  values.push(...vec);

  if (ids.length % 20 === 0) console.log(`  ${ids.length}/${corpus.length}`);
}

// Quantize to Int16: round(float * SCALE), clamp to [-32768, 32767]
const SCALE = 10000;
const quantized = new Int16Array(values.length);
for (let i = 0; i < values.length; i++) {
  const v = Math.round(values[i]! * SCALE);
  quantized[i] = Math.max(-32768, Math.min(32767, v));
}

const base64 = Buffer.from(quantized.buffer).toString("base64");

const outPath = join(import.meta.dir, "..", "src", "generated", "embeddings.ts");
const code = [
  "// Auto-generated by scripts/generate-embeddings.ts — do not edit manually.",
  `// Model: ${MODEL_NAME} (${DIM}-dim).`,
  `// Generated: ${new Date().toISOString()}`,
  `// Corpus: ${ids.length} items × ${DIM} dim`,
  "",
  `export const DIM = ${DIM} as const;`,
  `export const SCALE = ${SCALE} as const;`,
  `export const CORPUS_MODEL = ${JSON.stringify(MODEL_NAME)} as const;`,
  `export const VEC_IDS: readonly string[] = ${JSON.stringify(ids)};`,
  "",
  `// Quantized Int16 flat array (base64).`,
  `export const VEC_B64 = "${base64}";`,
].join("\n");

writeFileSync(outPath, code, "utf-8");
console.log(`\n✓ ${ids.length}×${DIM} (${quantized.byteLength} bytes) → ${outPath}`);
